#!/bin/bash
# Build Swift bindings for NearClip
# This script generates Swift bindings and builds the universal macOS library

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_DIR="$PROJECT_ROOT/target/swift"
FFI_CRATE="$PROJECT_ROOT/crates/nearclip-ffi"
UDL_FILE="$FFI_CRATE/src/nearclip.udl"

echo "=== NearClip Swift Bindings Build ==="
echo "Project root: $PROJECT_ROOT"
echo "Output directory: $OUTPUT_DIR"

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Step 1: Build uniffi-bindgen binary
echo ""
echo "=== Building uniffi-bindgen ==="
cargo build -p nearclip-ffi --bin uniffi-bindgen --release

UNIFFI_BINDGEN="$PROJECT_ROOT/target/release/uniffi-bindgen"

# Step 2: Generate Swift bindings
echo ""
echo "=== Generating Swift bindings ==="
"$UNIFFI_BINDGEN" generate "$UDL_FILE" \
    --language swift \
    --out-dir "$OUTPUT_DIR" \
    --config "$FFI_CRATE/uniffi.toml"

echo "Generated files:"
ls -la "$OUTPUT_DIR"

# Step 3: Build for Apple Silicon (arm64)
echo ""
echo "=== Building for Apple Silicon (aarch64-apple-darwin) ==="
if rustup target list --installed | grep -q "aarch64-apple-darwin"; then
    cargo build --release -p nearclip-ffi --target aarch64-apple-darwin
    ARM64_LIB="$PROJECT_ROOT/target/aarch64-apple-darwin/release/libnearclip_ffi.a"
else
    echo "aarch64-apple-darwin target not installed, skipping"
    ARM64_LIB=""
fi

# Step 4: Build for Intel (x86_64) - optional
echo ""
echo "=== Building for Intel (x86_64-apple-darwin) ==="
if rustup target list --installed | grep -q "x86_64-apple-darwin"; then
    cargo build --release -p nearclip-ffi --target x86_64-apple-darwin
    X86_64_LIB="$PROJECT_ROOT/target/x86_64-apple-darwin/release/libnearclip_ffi.a"
else
    echo "x86_64-apple-darwin target not installed, skipping"
    echo "To add it: rustup target add x86_64-apple-darwin"
    X86_64_LIB=""
fi

# Step 5: Create universal binary or copy available
echo ""
echo "=== Creating library ==="
UNIVERSAL_LIB="$OUTPUT_DIR/libnearclip_ffi.a"

if [ -n "$ARM64_LIB" ] && [ -f "$ARM64_LIB" ] && [ -n "$X86_64_LIB" ] && [ -f "$X86_64_LIB" ]; then
    echo "Creating universal binary..."
    lipo -create "$ARM64_LIB" "$X86_64_LIB" -output "$UNIVERSAL_LIB"
    echo "Created universal library: $UNIVERSAL_LIB"
    lipo -info "$UNIVERSAL_LIB"
elif [ -n "$ARM64_LIB" ] && [ -f "$ARM64_LIB" ]; then
    cp "$ARM64_LIB" "$UNIVERSAL_LIB"
    echo "Only arm64 library available, copied to output"
    lipo -info "$UNIVERSAL_LIB"
elif [ -n "$X86_64_LIB" ] && [ -f "$X86_64_LIB" ]; then
    cp "$X86_64_LIB" "$UNIVERSAL_LIB"
    echo "Only x86_64 library available, copied to output"
    lipo -info "$UNIVERSAL_LIB"
else
    echo "Error: No library files found!"
    exit 1
fi

# Step 6: Create XCFramework structure
echo ""
echo "=== Creating XCFramework structure ==="
XCFRAMEWORK_DIR="$OUTPUT_DIR/NearClip.xcframework"
MACOS_DIR="$XCFRAMEWORK_DIR/macos-arm64_x86_64"
rm -rf "$XCFRAMEWORK_DIR"
mkdir -p "$MACOS_DIR/Headers"

# Copy library
cp "$UNIVERSAL_LIB" "$MACOS_DIR/libnearclip_ffi.a"

# Copy header (generated by uniffi)
if [ -f "$OUTPUT_DIR/nearclipFFI.h" ]; then
    cp "$OUTPUT_DIR/nearclipFFI.h" "$MACOS_DIR/Headers/"
fi

# Copy module map
if [ -f "$OUTPUT_DIR/nearclipFFI.modulemap" ]; then
    cp "$OUTPUT_DIR/nearclipFFI.modulemap" "$MACOS_DIR/Headers/module.modulemap"
fi

# Create Info.plist
cat > "$XCFRAMEWORK_DIR/Info.plist" << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>AvailableLibraries</key>
    <array>
        <dict>
            <key>HeadersPath</key>
            <string>Headers</string>
            <key>LibraryIdentifier</key>
            <string>macos-arm64_x86_64</string>
            <key>LibraryPath</key>
            <string>libnearclip_ffi.a</string>
            <key>SupportedArchitectures</key>
            <array>
                <string>arm64</string>
                <string>x86_64</string>
            </array>
            <key>SupportedPlatform</key>
            <string>macos</string>
        </dict>
    </array>
    <key>CFBundlePackageType</key>
    <string>XFWK</string>
    <key>XCFrameworkFormatVersion</key>
    <string>1.0</string>
</dict>
</plist>
EOF

echo ""
echo "=== Build Complete ==="
echo ""
echo "Output files:"
echo "  Swift source:  $OUTPUT_DIR/nearclip.swift"
echo "  C header:      $OUTPUT_DIR/nearclipFFI.h"
echo "  Module map:    $OUTPUT_DIR/nearclipFFI.modulemap"
echo "  Static lib:    $OUTPUT_DIR/libnearclip_ffi.a"
echo "  XCFramework:   $XCFRAMEWORK_DIR"
echo ""
echo "To use in Xcode:"
echo "  1. Add $OUTPUT_DIR/nearclip.swift to your project"
echo "  2. Add $XCFRAMEWORK_DIR to your project frameworks"
echo "  3. In Build Settings, add to 'Library Search Paths': $OUTPUT_DIR"
echo ""
