default: build-all

build-core:
    cargo build -p clip_core --manifest-path core/Cargo.toml

build-android:
    cd platforms/android && \
    if [ -x ./gradlew ]; then ./gradlew assembleDebug; else gradle assembleDebug; fi

build-mac:
    cd platforms/mac && swift run

build-all:
    just build-core
    just build-android
    just build-mac
