default: build-all

build-core:
    cargo build -p clip_core --manifest-path core/Cargo.toml

build-bindings-ble:
    cargo build -p clip_core_bindings --manifest-path core/bindings/Cargo.toml --features ble

build-android:
    cd platforms/android && \
    if [ -x ./gradlew ]; then ./gradlew assembleDebug; else gradle assembleDebug; fi

build-mac:
    just build-bindings-ble
    cd platforms/mac && swift run

build-all:
    just build-core
    just build-android
    just build-mac
