// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(NearClipFFI)
import NearClipFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_nearclip_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_nearclip_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt16: FfiConverterPrimitive {
    typealias FfiType = Int16
    typealias SwiftType = Int16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int16, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol FfiNearClipManagerProtocol : AnyObject {
    
    func addHistoryEntry(entry: FfiSyncHistoryEntry) throws  -> Int64
    
    func addPairedDevice(device: FfiDeviceInfo) 
    
    func clearAllHistory() throws 
    
    func clearOldHistory(days: UInt32) throws  -> UInt64
    
    func connectDevice(deviceId: String) throws 
    
    func disconnectDevice(deviceId: String) throws 
    
    func getConnectedDevices()  -> [FfiDeviceInfo]
    
    func getDeviceHistory(deviceId: String, limit: UInt64) throws  -> [FfiSyncHistoryEntry]
    
    func getDeviceId()  -> String
    
    func getDeviceStatus(deviceId: String)  -> DeviceStatus?
    
    func getHistoryCount() throws  -> UInt64
    
    func getPairedDevices()  -> [FfiDeviceInfo]
    
    func getRecentHistory(limit: UInt64) throws  -> [FfiSyncHistoryEntry]
    
    func initHistory(dbPath: String) throws 
    
    func isRunning()  -> Bool
    
    func onBleConnectionChanged(deviceId: String, connected: Bool) 
    
    func onBleDataReceived(deviceId: String, data: Data) 
    
    func onBleDeviceDiscovered(peripheralUuid: String, deviceId: String, publicKeyHash: String, rssi: Int32) 
    
    func pairDevice(device: FfiDeviceInfo) throws  -> Bool
    
    func removePairedDevice(deviceId: String) 
    
    func setBleHardware(hardware: FfiBleHardware) 
    
    func setDeviceStorage(storage: FfiDeviceStorage) 
    
    func start() throws 
    
    func startDiscovery() 
    
    func stop() 
    
    func stopDiscovery() 
    
    func syncClipboard(content: Data) throws 
    
    func tryConnectPairedDevices()  -> UInt32
    
    func unpairDevice(deviceId: String) throws 
    
}

open class FfiNearClipManager:
    FfiNearClipManagerProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_nearclip_ffi_fn_clone_ffinearclipmanager(self.pointer, $0) }
    }
public convenience init(config: FfiNearClipConfig, callback: FfiNearClipCallback)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeNearClipError.lift) {
    uniffi_nearclip_ffi_fn_constructor_ffinearclipmanager_new(
        FfiConverterTypeFfiNearClipConfig.lower(config),
        FfiConverterCallbackInterfaceFfiNearClipCallback.lower(callback),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_nearclip_ffi_fn_free_ffinearclipmanager(pointer, $0) }
    }

    

    
open func addHistoryEntry(entry: FfiSyncHistoryEntry)throws  -> Int64 {
    return try  FfiConverterInt64.lift(try rustCallWithError(FfiConverterTypeNearClipError.lift) {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_add_history_entry(self.uniffiClonePointer(),
        FfiConverterTypeFfiSyncHistoryEntry.lower(entry),$0
    )
})
}
    
open func addPairedDevice(device: FfiDeviceInfo) {try! rustCall() {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_add_paired_device(self.uniffiClonePointer(),
        FfiConverterTypeFfiDeviceInfo.lower(device),$0
    )
}
}
    
open func clearAllHistory()throws  {try rustCallWithError(FfiConverterTypeNearClipError.lift) {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_clear_all_history(self.uniffiClonePointer(),$0
    )
}
}
    
open func clearOldHistory(days: UInt32)throws  -> UInt64 {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeNearClipError.lift) {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_clear_old_history(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(days),$0
    )
})
}
    
open func connectDevice(deviceId: String)throws  {try rustCallWithError(FfiConverterTypeNearClipError.lift) {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_connect_device(self.uniffiClonePointer(),
        FfiConverterString.lower(deviceId),$0
    )
}
}
    
open func disconnectDevice(deviceId: String)throws  {try rustCallWithError(FfiConverterTypeNearClipError.lift) {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_disconnect_device(self.uniffiClonePointer(),
        FfiConverterString.lower(deviceId),$0
    )
}
}
    
open func getConnectedDevices() -> [FfiDeviceInfo] {
    return try!  FfiConverterSequenceTypeFfiDeviceInfo.lift(try! rustCall() {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_get_connected_devices(self.uniffiClonePointer(),$0
    )
})
}
    
open func getDeviceHistory(deviceId: String, limit: UInt64)throws  -> [FfiSyncHistoryEntry] {
    return try  FfiConverterSequenceTypeFfiSyncHistoryEntry.lift(try rustCallWithError(FfiConverterTypeNearClipError.lift) {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_get_device_history(self.uniffiClonePointer(),
        FfiConverterString.lower(deviceId),
        FfiConverterUInt64.lower(limit),$0
    )
})
}
    
open func getDeviceId() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_get_device_id(self.uniffiClonePointer(),$0
    )
})
}
    
open func getDeviceStatus(deviceId: String) -> DeviceStatus? {
    return try!  FfiConverterOptionTypeDeviceStatus.lift(try! rustCall() {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_get_device_status(self.uniffiClonePointer(),
        FfiConverterString.lower(deviceId),$0
    )
})
}
    
open func getHistoryCount()throws  -> UInt64 {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeNearClipError.lift) {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_get_history_count(self.uniffiClonePointer(),$0
    )
})
}
    
open func getPairedDevices() -> [FfiDeviceInfo] {
    return try!  FfiConverterSequenceTypeFfiDeviceInfo.lift(try! rustCall() {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_get_paired_devices(self.uniffiClonePointer(),$0
    )
})
}
    
open func getRecentHistory(limit: UInt64)throws  -> [FfiSyncHistoryEntry] {
    return try  FfiConverterSequenceTypeFfiSyncHistoryEntry.lift(try rustCallWithError(FfiConverterTypeNearClipError.lift) {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_get_recent_history(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(limit),$0
    )
})
}
    
open func initHistory(dbPath: String)throws  {try rustCallWithError(FfiConverterTypeNearClipError.lift) {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_init_history(self.uniffiClonePointer(),
        FfiConverterString.lower(dbPath),$0
    )
}
}
    
open func isRunning() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_is_running(self.uniffiClonePointer(),$0
    )
})
}
    
open func onBleConnectionChanged(deviceId: String, connected: Bool) {try! rustCall() {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_on_ble_connection_changed(self.uniffiClonePointer(),
        FfiConverterString.lower(deviceId),
        FfiConverterBool.lower(connected),$0
    )
}
}
    
open func onBleDataReceived(deviceId: String, data: Data) {try! rustCall() {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_on_ble_data_received(self.uniffiClonePointer(),
        FfiConverterString.lower(deviceId),
        FfiConverterData.lower(data),$0
    )
}
}
    
open func onBleDeviceDiscovered(peripheralUuid: String, deviceId: String, publicKeyHash: String, rssi: Int32) {try! rustCall() {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_on_ble_device_discovered(self.uniffiClonePointer(),
        FfiConverterString.lower(peripheralUuid),
        FfiConverterString.lower(deviceId),
        FfiConverterString.lower(publicKeyHash),
        FfiConverterInt32.lower(rssi),$0
    )
}
}
    
open func pairDevice(device: FfiDeviceInfo)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeNearClipError.lift) {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_pair_device(self.uniffiClonePointer(),
        FfiConverterTypeFfiDeviceInfo.lower(device),$0
    )
})
}
    
open func removePairedDevice(deviceId: String) {try! rustCall() {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_remove_paired_device(self.uniffiClonePointer(),
        FfiConverterString.lower(deviceId),$0
    )
}
}
    
open func setBleHardware(hardware: FfiBleHardware) {try! rustCall() {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_set_ble_hardware(self.uniffiClonePointer(),
        FfiConverterCallbackInterfaceFfiBleHardware.lower(hardware),$0
    )
}
}
    
open func setDeviceStorage(storage: FfiDeviceStorage) {try! rustCall() {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_set_device_storage(self.uniffiClonePointer(),
        FfiConverterCallbackInterfaceFfiDeviceStorage.lower(storage),$0
    )
}
}
    
open func start()throws  {try rustCallWithError(FfiConverterTypeNearClipError.lift) {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_start(self.uniffiClonePointer(),$0
    )
}
}
    
open func startDiscovery() {try! rustCall() {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_start_discovery(self.uniffiClonePointer(),$0
    )
}
}
    
open func stop() {try! rustCall() {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_stop(self.uniffiClonePointer(),$0
    )
}
}
    
open func stopDiscovery() {try! rustCall() {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_stop_discovery(self.uniffiClonePointer(),$0
    )
}
}
    
open func syncClipboard(content: Data)throws  {try rustCallWithError(FfiConverterTypeNearClipError.lift) {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_sync_clipboard(self.uniffiClonePointer(),
        FfiConverterData.lower(content),$0
    )
}
}
    
open func tryConnectPairedDevices() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_try_connect_paired_devices(self.uniffiClonePointer(),$0
    )
})
}
    
open func unpairDevice(deviceId: String)throws  {try rustCallWithError(FfiConverterTypeNearClipError.lift) {
    uniffi_nearclip_ffi_fn_method_ffinearclipmanager_unpair_device(self.uniffiClonePointer(),
        FfiConverterString.lower(deviceId),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiNearClipManager: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FfiNearClipManager

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiNearClipManager {
        return FfiNearClipManager(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FfiNearClipManager) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiNearClipManager {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FfiNearClipManager, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiNearClipManager_lift(_ pointer: UnsafeMutableRawPointer) throws -> FfiNearClipManager {
    return try FfiConverterTypeFfiNearClipManager.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiNearClipManager_lower(_ value: FfiNearClipManager) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFfiNearClipManager.lower(value)
}


public struct FfiDeviceInfo {
    public var id: String
    public var name: String
    public var platform: DevicePlatform
    public var status: DeviceStatus

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, platform: DevicePlatform, status: DeviceStatus) {
        self.id = id
        self.name = name
        self.platform = platform
        self.status = status
    }
}



extension FfiDeviceInfo: Equatable, Hashable {
    public static func ==(lhs: FfiDeviceInfo, rhs: FfiDeviceInfo) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.platform != rhs.platform {
            return false
        }
        if lhs.status != rhs.status {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(name)
        hasher.combine(platform)
        hasher.combine(status)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiDeviceInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiDeviceInfo {
        return
            try FfiDeviceInfo(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                platform: FfiConverterTypeDevicePlatform.read(from: &buf), 
                status: FfiConverterTypeDeviceStatus.read(from: &buf)
        )
    }

    public static func write(_ value: FfiDeviceInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterTypeDevicePlatform.write(value.platform, into: &buf)
        FfiConverterTypeDeviceStatus.write(value.status, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDeviceInfo_lift(_ buf: RustBuffer) throws -> FfiDeviceInfo {
    return try FfiConverterTypeFfiDeviceInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDeviceInfo_lower(_ value: FfiDeviceInfo) -> RustBuffer {
    return FfiConverterTypeFfiDeviceInfo.lower(value)
}


public struct FfiDiscoveredDevice {
    public var peripheralUuid: String
    public var deviceName: String?
    public var rssi: Int16
    public var publicKeyHash: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(peripheralUuid: String, deviceName: String?, rssi: Int16, publicKeyHash: String?) {
        self.peripheralUuid = peripheralUuid
        self.deviceName = deviceName
        self.rssi = rssi
        self.publicKeyHash = publicKeyHash
    }
}



extension FfiDiscoveredDevice: Equatable, Hashable {
    public static func ==(lhs: FfiDiscoveredDevice, rhs: FfiDiscoveredDevice) -> Bool {
        if lhs.peripheralUuid != rhs.peripheralUuid {
            return false
        }
        if lhs.deviceName != rhs.deviceName {
            return false
        }
        if lhs.rssi != rhs.rssi {
            return false
        }
        if lhs.publicKeyHash != rhs.publicKeyHash {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(peripheralUuid)
        hasher.combine(deviceName)
        hasher.combine(rssi)
        hasher.combine(publicKeyHash)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiDiscoveredDevice: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiDiscoveredDevice {
        return
            try FfiDiscoveredDevice(
                peripheralUuid: FfiConverterString.read(from: &buf), 
                deviceName: FfiConverterOptionString.read(from: &buf), 
                rssi: FfiConverterInt16.read(from: &buf), 
                publicKeyHash: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiDiscoveredDevice, into buf: inout [UInt8]) {
        FfiConverterString.write(value.peripheralUuid, into: &buf)
        FfiConverterOptionString.write(value.deviceName, into: &buf)
        FfiConverterInt16.write(value.rssi, into: &buf)
        FfiConverterOptionString.write(value.publicKeyHash, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDiscoveredDevice_lift(_ buf: RustBuffer) throws -> FfiDiscoveredDevice {
    return try FfiConverterTypeFfiDiscoveredDevice.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDiscoveredDevice_lower(_ value: FfiDiscoveredDevice) -> RustBuffer {
    return FfiConverterTypeFfiDiscoveredDevice.lower(value)
}


public struct FfiNearClipConfig {
    public var deviceName: String
    public var deviceId: String
    public var wifiEnabled: Bool
    public var bleEnabled: Bool
    public var autoConnect: Bool
    public var connectionTimeoutSecs: UInt64
    public var heartbeatIntervalSecs: UInt64
    public var maxRetries: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(deviceName: String, deviceId: String, wifiEnabled: Bool, bleEnabled: Bool, autoConnect: Bool, connectionTimeoutSecs: UInt64, heartbeatIntervalSecs: UInt64, maxRetries: UInt32) {
        self.deviceName = deviceName
        self.deviceId = deviceId
        self.wifiEnabled = wifiEnabled
        self.bleEnabled = bleEnabled
        self.autoConnect = autoConnect
        self.connectionTimeoutSecs = connectionTimeoutSecs
        self.heartbeatIntervalSecs = heartbeatIntervalSecs
        self.maxRetries = maxRetries
    }
}



extension FfiNearClipConfig: Equatable, Hashable {
    public static func ==(lhs: FfiNearClipConfig, rhs: FfiNearClipConfig) -> Bool {
        if lhs.deviceName != rhs.deviceName {
            return false
        }
        if lhs.deviceId != rhs.deviceId {
            return false
        }
        if lhs.wifiEnabled != rhs.wifiEnabled {
            return false
        }
        if lhs.bleEnabled != rhs.bleEnabled {
            return false
        }
        if lhs.autoConnect != rhs.autoConnect {
            return false
        }
        if lhs.connectionTimeoutSecs != rhs.connectionTimeoutSecs {
            return false
        }
        if lhs.heartbeatIntervalSecs != rhs.heartbeatIntervalSecs {
            return false
        }
        if lhs.maxRetries != rhs.maxRetries {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(deviceName)
        hasher.combine(deviceId)
        hasher.combine(wifiEnabled)
        hasher.combine(bleEnabled)
        hasher.combine(autoConnect)
        hasher.combine(connectionTimeoutSecs)
        hasher.combine(heartbeatIntervalSecs)
        hasher.combine(maxRetries)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiNearClipConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiNearClipConfig {
        return
            try FfiNearClipConfig(
                deviceName: FfiConverterString.read(from: &buf), 
                deviceId: FfiConverterString.read(from: &buf), 
                wifiEnabled: FfiConverterBool.read(from: &buf), 
                bleEnabled: FfiConverterBool.read(from: &buf), 
                autoConnect: FfiConverterBool.read(from: &buf), 
                connectionTimeoutSecs: FfiConverterUInt64.read(from: &buf), 
                heartbeatIntervalSecs: FfiConverterUInt64.read(from: &buf), 
                maxRetries: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FfiNearClipConfig, into buf: inout [UInt8]) {
        FfiConverterString.write(value.deviceName, into: &buf)
        FfiConverterString.write(value.deviceId, into: &buf)
        FfiConverterBool.write(value.wifiEnabled, into: &buf)
        FfiConverterBool.write(value.bleEnabled, into: &buf)
        FfiConverterBool.write(value.autoConnect, into: &buf)
        FfiConverterUInt64.write(value.connectionTimeoutSecs, into: &buf)
        FfiConverterUInt64.write(value.heartbeatIntervalSecs, into: &buf)
        FfiConverterUInt32.write(value.maxRetries, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiNearClipConfig_lift(_ buf: RustBuffer) throws -> FfiNearClipConfig {
    return try FfiConverterTypeFfiNearClipConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiNearClipConfig_lower(_ value: FfiNearClipConfig) -> RustBuffer {
    return FfiConverterTypeFfiNearClipConfig.lower(value)
}


public struct FfiSyncHistoryEntry {
    public var id: Int64
    public var deviceId: String
    public var deviceName: String
    public var contentPreview: String
    public var contentSize: UInt64
    public var direction: String
    public var timestampMs: Int64
    public var success: Bool
    public var errorMessage: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: Int64, deviceId: String, deviceName: String, contentPreview: String, contentSize: UInt64, direction: String, timestampMs: Int64, success: Bool, errorMessage: String?) {
        self.id = id
        self.deviceId = deviceId
        self.deviceName = deviceName
        self.contentPreview = contentPreview
        self.contentSize = contentSize
        self.direction = direction
        self.timestampMs = timestampMs
        self.success = success
        self.errorMessage = errorMessage
    }
}



extension FfiSyncHistoryEntry: Equatable, Hashable {
    public static func ==(lhs: FfiSyncHistoryEntry, rhs: FfiSyncHistoryEntry) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.deviceId != rhs.deviceId {
            return false
        }
        if lhs.deviceName != rhs.deviceName {
            return false
        }
        if lhs.contentPreview != rhs.contentPreview {
            return false
        }
        if lhs.contentSize != rhs.contentSize {
            return false
        }
        if lhs.direction != rhs.direction {
            return false
        }
        if lhs.timestampMs != rhs.timestampMs {
            return false
        }
        if lhs.success != rhs.success {
            return false
        }
        if lhs.errorMessage != rhs.errorMessage {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(deviceId)
        hasher.combine(deviceName)
        hasher.combine(contentPreview)
        hasher.combine(contentSize)
        hasher.combine(direction)
        hasher.combine(timestampMs)
        hasher.combine(success)
        hasher.combine(errorMessage)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSyncHistoryEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSyncHistoryEntry {
        return
            try FfiSyncHistoryEntry(
                id: FfiConverterInt64.read(from: &buf), 
                deviceId: FfiConverterString.read(from: &buf), 
                deviceName: FfiConverterString.read(from: &buf), 
                contentPreview: FfiConverterString.read(from: &buf), 
                contentSize: FfiConverterUInt64.read(from: &buf), 
                direction: FfiConverterString.read(from: &buf), 
                timestampMs: FfiConverterInt64.read(from: &buf), 
                success: FfiConverterBool.read(from: &buf), 
                errorMessage: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiSyncHistoryEntry, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.id, into: &buf)
        FfiConverterString.write(value.deviceId, into: &buf)
        FfiConverterString.write(value.deviceName, into: &buf)
        FfiConverterString.write(value.contentPreview, into: &buf)
        FfiConverterUInt64.write(value.contentSize, into: &buf)
        FfiConverterString.write(value.direction, into: &buf)
        FfiConverterInt64.write(value.timestampMs, into: &buf)
        FfiConverterBool.write(value.success, into: &buf)
        FfiConverterOptionString.write(value.errorMessage, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSyncHistoryEntry_lift(_ buf: RustBuffer) throws -> FfiSyncHistoryEntry {
    return try FfiConverterTypeFfiSyncHistoryEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSyncHistoryEntry_lower(_ value: FfiSyncHistoryEntry) -> RustBuffer {
    return FfiConverterTypeFfiSyncHistoryEntry.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum DevicePlatform {
    
    case macOs
    case android
    case unknown
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDevicePlatform: FfiConverterRustBuffer {
    typealias SwiftType = DevicePlatform

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DevicePlatform {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .macOs
        
        case 2: return .android
        
        case 3: return .unknown
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DevicePlatform, into buf: inout [UInt8]) {
        switch value {
        
        
        case .macOs:
            writeInt(&buf, Int32(1))
        
        
        case .android:
            writeInt(&buf, Int32(2))
        
        
        case .unknown:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDevicePlatform_lift(_ buf: RustBuffer) throws -> DevicePlatform {
    return try FfiConverterTypeDevicePlatform.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDevicePlatform_lower(_ value: DevicePlatform) -> RustBuffer {
    return FfiConverterTypeDevicePlatform.lower(value)
}



extension DevicePlatform: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum DeviceStatus {
    
    case connected
    case disconnected
    case connecting
    case failed
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDeviceStatus: FfiConverterRustBuffer {
    typealias SwiftType = DeviceStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DeviceStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .connected
        
        case 2: return .disconnected
        
        case 3: return .connecting
        
        case 4: return .failed
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DeviceStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .connected:
            writeInt(&buf, Int32(1))
        
        
        case .disconnected:
            writeInt(&buf, Int32(2))
        
        
        case .connecting:
            writeInt(&buf, Int32(3))
        
        
        case .failed:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDeviceStatus_lift(_ buf: RustBuffer) throws -> DeviceStatus {
    return try FfiConverterTypeDeviceStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDeviceStatus_lower(_ value: DeviceStatus) -> RustBuffer {
    return FfiConverterTypeDeviceStatus.lower(value)
}



extension DeviceStatus: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum LogLevel {
    
    case error
    case warn
    case info
    case debug
    case trace
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLogLevel: FfiConverterRustBuffer {
    typealias SwiftType = LogLevel

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LogLevel {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .error
        
        case 2: return .warn
        
        case 3: return .info
        
        case 4: return .debug
        
        case 5: return .trace
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: LogLevel, into buf: inout [UInt8]) {
        switch value {
        
        
        case .error:
            writeInt(&buf, Int32(1))
        
        
        case .warn:
            writeInt(&buf, Int32(2))
        
        
        case .info:
            writeInt(&buf, Int32(3))
        
        
        case .debug:
            writeInt(&buf, Int32(4))
        
        
        case .trace:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLogLevel_lift(_ buf: RustBuffer) throws -> LogLevel {
    return try FfiConverterTypeLogLevel.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLogLevel_lower(_ value: LogLevel) -> RustBuffer {
    return FfiConverterTypeLogLevel.lower(value)
}



extension LogLevel: Equatable, Hashable {}




public enum NearClipError {

    
    
    case Network(message: String)
    
    case Bluetooth(message: String)
    
    case Crypto(message: String)
    
    case DeviceNotFound(message: String)
    
    case Sync(message: String)
    
    case Config(message: String)
    
    case Io(message: String)
    
    case NotInitialized(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNearClipError: FfiConverterRustBuffer {
    typealias SwiftType = NearClipError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NearClipError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Network(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .Bluetooth(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .Crypto(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .DeviceNotFound(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .Sync(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .Config(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .Io(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .NotInitialized(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NearClipError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Network(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .Bluetooth(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .Crypto(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .DeviceNotFound(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .Sync(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .Config(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .Io(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))
        case .NotInitialized(_ /* message is ignored*/):
            writeInt(&buf, Int32(8))

        
        }
    }
}


extension NearClipError: Equatable, Hashable {}

extension NearClipError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




public protocol FfiBleHardware : AnyObject {
    
    func startScan() 
    
    func stopScan() 
    
    func connect(peripheralUuid: String) 
    
    func disconnect(peripheralUuid: String) 
    
    func readCharacteristic(peripheralUuid: String, charUuid: String)  -> Data
    
    func writeCharacteristic(peripheralUuid: String, charUuid: String, data: Data)  -> String
    
    func subscribeCharacteristic(peripheralUuid: String, charUuid: String)  -> String
    
    func startAdvertising(serviceData: Data) 
    
    func stopAdvertising() 
    
    func isConnected(peripheralUuid: String)  -> Bool
    
    func getMtu(peripheralUuid: String)  -> UInt32
    
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceFfiBleHardware {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceFfiBleHardware = UniffiVTableCallbackInterfaceFfiBleHardware(
        startScan: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiBleHardware.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.startScan(
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        stopScan: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiBleHardware.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.stopScan(
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        connect: { (
            uniffiHandle: UInt64,
            peripheralUuid: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiBleHardware.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.connect(
                     peripheralUuid: try FfiConverterString.lift(peripheralUuid)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        disconnect: { (
            uniffiHandle: UInt64,
            peripheralUuid: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiBleHardware.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.disconnect(
                     peripheralUuid: try FfiConverterString.lift(peripheralUuid)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        readCharacteristic: { (
            uniffiHandle: UInt64,
            peripheralUuid: RustBuffer,
            charUuid: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Data in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiBleHardware.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.readCharacteristic(
                     peripheralUuid: try FfiConverterString.lift(peripheralUuid),
                     charUuid: try FfiConverterString.lift(charUuid)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterData.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        writeCharacteristic: { (
            uniffiHandle: UInt64,
            peripheralUuid: RustBuffer,
            charUuid: RustBuffer,
            data: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> String in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiBleHardware.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.writeCharacteristic(
                     peripheralUuid: try FfiConverterString.lift(peripheralUuid),
                     charUuid: try FfiConverterString.lift(charUuid),
                     data: try FfiConverterData.lift(data)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterString.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        subscribeCharacteristic: { (
            uniffiHandle: UInt64,
            peripheralUuid: RustBuffer,
            charUuid: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> String in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiBleHardware.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.subscribeCharacteristic(
                     peripheralUuid: try FfiConverterString.lift(peripheralUuid),
                     charUuid: try FfiConverterString.lift(charUuid)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterString.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        startAdvertising: { (
            uniffiHandle: UInt64,
            serviceData: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiBleHardware.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.startAdvertising(
                     serviceData: try FfiConverterData.lift(serviceData)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        stopAdvertising: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiBleHardware.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.stopAdvertising(
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        isConnected: { (
            uniffiHandle: UInt64,
            peripheralUuid: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<Int8>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Bool in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiBleHardware.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.isConnected(
                     peripheralUuid: try FfiConverterString.lift(peripheralUuid)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterBool.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        getMtu: { (
            uniffiHandle: UInt64,
            peripheralUuid: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<UInt32>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> UInt32 in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiBleHardware.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.getMtu(
                     peripheralUuid: try FfiConverterString.lift(peripheralUuid)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterUInt32.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceFfiBleHardware.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface FfiBleHardware: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitFfiBleHardware() {
    uniffi_nearclip_ffi_fn_init_callback_vtable_ffiblehardware(&UniffiCallbackInterfaceFfiBleHardware.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceFfiBleHardware {
    fileprivate static var handleMap = UniffiHandleMap<FfiBleHardware>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceFfiBleHardware : FfiConverter {
    typealias SwiftType = FfiBleHardware
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}




public protocol FfiDeviceStorage : AnyObject {
    
    func saveDevice(device: FfiDeviceInfo) 
    
    func removeDevice(deviceId: String) 
    
    func loadAllDevices()  -> [FfiDeviceInfo]
    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceFfiDeviceStorage {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceFfiDeviceStorage = UniffiVTableCallbackInterfaceFfiDeviceStorage(
        saveDevice: { (
            uniffiHandle: UInt64,
            device: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiDeviceStorage.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.saveDevice(
                     device: try FfiConverterTypeFfiDeviceInfo.lift(device)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        removeDevice: { (
            uniffiHandle: UInt64,
            deviceId: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiDeviceStorage.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.removeDevice(
                     deviceId: try FfiConverterString.lift(deviceId)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        loadAllDevices: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> [FfiDeviceInfo] in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiDeviceStorage.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.loadAllDevices(
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterSequenceTypeFfiDeviceInfo.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceFfiDeviceStorage.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface FfiDeviceStorage: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitFfiDeviceStorage() {
    uniffi_nearclip_ffi_fn_init_callback_vtable_ffidevicestorage(&UniffiCallbackInterfaceFfiDeviceStorage.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceFfiDeviceStorage {
    fileprivate static var handleMap = UniffiHandleMap<FfiDeviceStorage>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceFfiDeviceStorage : FfiConverter {
    typealias SwiftType = FfiDeviceStorage
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}




public protocol FfiNearClipCallback : AnyObject {
    
    func onDeviceConnected(device: FfiDeviceInfo) 
    
    func onDeviceDisconnected(deviceId: String) 
    
    func onDeviceUnpaired(deviceId: String) 
    
    func onPairingRejected(deviceId: String, reason: String) 
    
    func onClipboardReceived(content: Data, fromDevice: String) 
    
    func onSyncError(errorMessage: String) 
    
    func onDeviceDiscovered(device: FfiDiscoveredDevice) 
    
    func onDeviceLost(peripheralUuid: String) 
    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceFfiNearClipCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceFfiNearClipCallback = UniffiVTableCallbackInterfaceFfiNearClipCallback(
        onDeviceConnected: { (
            uniffiHandle: UInt64,
            device: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiNearClipCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onDeviceConnected(
                     device: try FfiConverterTypeFfiDeviceInfo.lift(device)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onDeviceDisconnected: { (
            uniffiHandle: UInt64,
            deviceId: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiNearClipCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onDeviceDisconnected(
                     deviceId: try FfiConverterString.lift(deviceId)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onDeviceUnpaired: { (
            uniffiHandle: UInt64,
            deviceId: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiNearClipCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onDeviceUnpaired(
                     deviceId: try FfiConverterString.lift(deviceId)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onPairingRejected: { (
            uniffiHandle: UInt64,
            deviceId: RustBuffer,
            reason: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiNearClipCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onPairingRejected(
                     deviceId: try FfiConverterString.lift(deviceId),
                     reason: try FfiConverterString.lift(reason)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onClipboardReceived: { (
            uniffiHandle: UInt64,
            content: RustBuffer,
            fromDevice: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiNearClipCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onClipboardReceived(
                     content: try FfiConverterData.lift(content),
                     fromDevice: try FfiConverterString.lift(fromDevice)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onSyncError: { (
            uniffiHandle: UInt64,
            errorMessage: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiNearClipCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onSyncError(
                     errorMessage: try FfiConverterString.lift(errorMessage)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onDeviceDiscovered: { (
            uniffiHandle: UInt64,
            device: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiNearClipCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onDeviceDiscovered(
                     device: try FfiConverterTypeFfiDiscoveredDevice.lift(device)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onDeviceLost: { (
            uniffiHandle: UInt64,
            peripheralUuid: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceFfiNearClipCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onDeviceLost(
                     peripheralUuid: try FfiConverterString.lift(peripheralUuid)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceFfiNearClipCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface FfiNearClipCallback: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitFfiNearClipCallback() {
    uniffi_nearclip_ffi_fn_init_callback_vtable_ffinearclipcallback(&UniffiCallbackInterfaceFfiNearClipCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceFfiNearClipCallback {
    fileprivate static var handleMap = UniffiHandleMap<FfiNearClipCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceFfiNearClipCallback : FfiConverter {
    typealias SwiftType = FfiNearClipCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeDeviceStatus: FfiConverterRustBuffer {
    typealias SwiftType = DeviceStatus?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeDeviceStatus.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeDeviceStatus.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiDeviceInfo: FfiConverterRustBuffer {
    typealias SwiftType = [FfiDeviceInfo]

    public static func write(_ value: [FfiDeviceInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiDeviceInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiDeviceInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiDeviceInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiDeviceInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiSyncHistoryEntry: FfiConverterRustBuffer {
    typealias SwiftType = [FfiSyncHistoryEntry]

    public static func write(_ value: [FfiSyncHistoryEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiSyncHistoryEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiSyncHistoryEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiSyncHistoryEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiSyncHistoryEntry.read(from: &buf))
        }
        return seq
    }
}
public func flushLogs() {try! rustCall() {
    uniffi_nearclip_ffi_fn_func_flush_logs($0
    )
}
}
public func initLogging(level: LogLevel) {try! rustCall() {
    uniffi_nearclip_ffi_fn_func_init_logging(
        FfiConverterTypeLogLevel.lower(level),$0
    )
}
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_nearclip_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_nearclip_ffi_checksum_func_flush_logs() != 62970) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_func_init_logging() != 1565) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_add_history_entry() != 4174) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_add_paired_device() != 60193) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_clear_all_history() != 17682) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_clear_old_history() != 22006) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_connect_device() != 8194) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_disconnect_device() != 58683) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_get_connected_devices() != 29571) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_get_device_history() != 32499) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_get_device_id() != 57304) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_get_device_status() != 59586) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_get_history_count() != 5747) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_get_paired_devices() != 18870) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_get_recent_history() != 41751) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_init_history() != 15508) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_is_running() != 27473) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_on_ble_connection_changed() != 5720) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_on_ble_data_received() != 44728) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_on_ble_device_discovered() != 59927) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_pair_device() != 30453) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_remove_paired_device() != 5261) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_set_ble_hardware() != 20925) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_set_device_storage() != 56416) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_start() != 22762) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_start_discovery() != 64753) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_stop() != 39976) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_stop_discovery() != 58572) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_sync_clipboard() != 17869) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_try_connect_paired_devices() != 18103) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_unpair_device() != 63811) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_constructor_ffinearclipmanager_new() != 16624) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffiblehardware_start_scan() != 49057) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffiblehardware_stop_scan() != 40413) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffiblehardware_connect() != 53678) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffiblehardware_disconnect() != 19327) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffiblehardware_read_characteristic() != 10510) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffiblehardware_write_characteristic() != 7268) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffiblehardware_subscribe_characteristic() != 40611) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffiblehardware_start_advertising() != 19708) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffiblehardware_stop_advertising() != 51147) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffiblehardware_is_connected() != 50619) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffiblehardware_get_mtu() != 8130) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffidevicestorage_save_device() != 17485) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffidevicestorage_remove_device() != 51784) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffidevicestorage_load_all_devices() != 6363) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipcallback_on_device_connected() != 23454) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipcallback_on_device_disconnected() != 31870) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipcallback_on_device_unpaired() != 10576) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipcallback_on_pairing_rejected() != 26516) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipcallback_on_clipboard_received() != 47039) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipcallback_on_sync_error() != 15126) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipcallback_on_device_discovered() != 20976) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nearclip_ffi_checksum_method_ffinearclipcallback_on_device_lost() != 14553) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitFfiBleHardware()
    uniffiCallbackInitFfiDeviceStorage()
    uniffiCallbackInitFfiNearClipCallback()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all