name: Build Apps

on:
  push:
  pull_request:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Rust core
        run: cargo build -p clip_core --manifest-path core/Cargo.toml
      - name: Build Android app
        run: cd platforms/android && ./gradlew assembleDebug

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Rust core
        run: cargo build -p clip_core --manifest-path core/Cargo.toml
      - name: Build macOS app
        run: cd platforms/mac && swift build -c release
