// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD0
typedef void (*UniffiCallbackInterfaceFfiBleHardwareMethod0)(uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD1
typedef void (*UniffiCallbackInterfaceFfiBleHardwareMethod1)(uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD2
typedef void (*UniffiCallbackInterfaceFfiBleHardwareMethod2)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD3
typedef void (*UniffiCallbackInterfaceFfiBleHardwareMethod3)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD4
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD4
typedef void (*UniffiCallbackInterfaceFfiBleHardwareMethod4)(uint64_t, RustBuffer, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD5
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD5
typedef void (*UniffiCallbackInterfaceFfiBleHardwareMethod5)(uint64_t, RustBuffer, RustBuffer, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD6
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD6
typedef void (*UniffiCallbackInterfaceFfiBleHardwareMethod6)(uint64_t, RustBuffer, RustBuffer, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD7
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD7
typedef void (*UniffiCallbackInterfaceFfiBleHardwareMethod7)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD8
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD8
typedef void (*UniffiCallbackInterfaceFfiBleHardwareMethod8)(uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD9
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD9
typedef void (*UniffiCallbackInterfaceFfiBleHardwareMethod9)(uint64_t, RustBuffer, int8_t* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD10
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_BLE_HARDWARE_METHOD10
typedef void (*UniffiCallbackInterfaceFfiBleHardwareMethod10)(uint64_t, RustBuffer, uint32_t* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_DEVICE_STORAGE_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_DEVICE_STORAGE_METHOD0
typedef void (*UniffiCallbackInterfaceFfiDeviceStorageMethod0)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_DEVICE_STORAGE_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_DEVICE_STORAGE_METHOD1
typedef void (*UniffiCallbackInterfaceFfiDeviceStorageMethod1)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_DEVICE_STORAGE_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_DEVICE_STORAGE_METHOD2
typedef void (*UniffiCallbackInterfaceFfiDeviceStorageMethod2)(uint64_t, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_NEAR_CLIP_CALLBACK_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_NEAR_CLIP_CALLBACK_METHOD0
typedef void (*UniffiCallbackInterfaceFfiNearClipCallbackMethod0)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_NEAR_CLIP_CALLBACK_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_NEAR_CLIP_CALLBACK_METHOD1
typedef void (*UniffiCallbackInterfaceFfiNearClipCallbackMethod1)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_NEAR_CLIP_CALLBACK_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_NEAR_CLIP_CALLBACK_METHOD2
typedef void (*UniffiCallbackInterfaceFfiNearClipCallbackMethod2)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_NEAR_CLIP_CALLBACK_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_NEAR_CLIP_CALLBACK_METHOD3
typedef void (*UniffiCallbackInterfaceFfiNearClipCallbackMethod3)(uint64_t, RustBuffer, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_NEAR_CLIP_CALLBACK_METHOD4
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_NEAR_CLIP_CALLBACK_METHOD4
typedef void (*UniffiCallbackInterfaceFfiNearClipCallbackMethod4)(uint64_t, RustBuffer, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_NEAR_CLIP_CALLBACK_METHOD5
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_NEAR_CLIP_CALLBACK_METHOD5
typedef void (*UniffiCallbackInterfaceFfiNearClipCallbackMethod5)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_NEAR_CLIP_CALLBACK_METHOD6
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_NEAR_CLIP_CALLBACK_METHOD6
typedef void (*UniffiCallbackInterfaceFfiNearClipCallbackMethod6)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_NEAR_CLIP_CALLBACK_METHOD7
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FFI_NEAR_CLIP_CALLBACK_METHOD7
typedef void (*UniffiCallbackInterfaceFfiNearClipCallbackMethod7)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_FFI_BLE_HARDWARE
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_FFI_BLE_HARDWARE
typedef struct UniffiVTableCallbackInterfaceFfiBleHardware {
    UniffiCallbackInterfaceFfiBleHardwareMethod0 _Nonnull startScan;
    UniffiCallbackInterfaceFfiBleHardwareMethod1 _Nonnull stopScan;
    UniffiCallbackInterfaceFfiBleHardwareMethod2 _Nonnull connect;
    UniffiCallbackInterfaceFfiBleHardwareMethod3 _Nonnull disconnect;
    UniffiCallbackInterfaceFfiBleHardwareMethod4 _Nonnull readCharacteristic;
    UniffiCallbackInterfaceFfiBleHardwareMethod5 _Nonnull writeCharacteristic;
    UniffiCallbackInterfaceFfiBleHardwareMethod6 _Nonnull subscribeCharacteristic;
    UniffiCallbackInterfaceFfiBleHardwareMethod7 _Nonnull startAdvertising;
    UniffiCallbackInterfaceFfiBleHardwareMethod8 _Nonnull stopAdvertising;
    UniffiCallbackInterfaceFfiBleHardwareMethod9 _Nonnull isConnected;
    UniffiCallbackInterfaceFfiBleHardwareMethod10 _Nonnull getMtu;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceFfiBleHardware;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_FFI_DEVICE_STORAGE
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_FFI_DEVICE_STORAGE
typedef struct UniffiVTableCallbackInterfaceFfiDeviceStorage {
    UniffiCallbackInterfaceFfiDeviceStorageMethod0 _Nonnull saveDevice;
    UniffiCallbackInterfaceFfiDeviceStorageMethod1 _Nonnull removeDevice;
    UniffiCallbackInterfaceFfiDeviceStorageMethod2 _Nonnull loadAllDevices;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceFfiDeviceStorage;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_FFI_NEAR_CLIP_CALLBACK
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_FFI_NEAR_CLIP_CALLBACK
typedef struct UniffiVTableCallbackInterfaceFfiNearClipCallback {
    UniffiCallbackInterfaceFfiNearClipCallbackMethod0 _Nonnull onDeviceConnected;
    UniffiCallbackInterfaceFfiNearClipCallbackMethod1 _Nonnull onDeviceDisconnected;
    UniffiCallbackInterfaceFfiNearClipCallbackMethod2 _Nonnull onDeviceUnpaired;
    UniffiCallbackInterfaceFfiNearClipCallbackMethod3 _Nonnull onPairingRejected;
    UniffiCallbackInterfaceFfiNearClipCallbackMethod4 _Nonnull onClipboardReceived;
    UniffiCallbackInterfaceFfiNearClipCallbackMethod5 _Nonnull onSyncError;
    UniffiCallbackInterfaceFfiNearClipCallbackMethod6 _Nonnull onDeviceDiscovered;
    UniffiCallbackInterfaceFfiNearClipCallbackMethod7 _Nonnull onDeviceLost;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceFfiNearClipCallback;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_CLONE_FFINEARCLIPMANAGER
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_CLONE_FFINEARCLIPMANAGER
void*_Nonnull uniffi_nearclip_ffi_fn_clone_ffinearclipmanager(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_FREE_FFINEARCLIPMANAGER
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_FREE_FFINEARCLIPMANAGER
void uniffi_nearclip_ffi_fn_free_ffinearclipmanager(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_CONSTRUCTOR_FFINEARCLIPMANAGER_NEW
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_CONSTRUCTOR_FFINEARCLIPMANAGER_NEW
void*_Nonnull uniffi_nearclip_ffi_fn_constructor_ffinearclipmanager_new(RustBuffer config, uint64_t callback, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_ADD_HISTORY_ENTRY
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_ADD_HISTORY_ENTRY
int64_t uniffi_nearclip_ffi_fn_method_ffinearclipmanager_add_history_entry(void*_Nonnull ptr, RustBuffer entry, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_ADD_PAIRED_DEVICE
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_ADD_PAIRED_DEVICE
void uniffi_nearclip_ffi_fn_method_ffinearclipmanager_add_paired_device(void*_Nonnull ptr, RustBuffer device, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_CLEAR_ALL_HISTORY
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_CLEAR_ALL_HISTORY
void uniffi_nearclip_ffi_fn_method_ffinearclipmanager_clear_all_history(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_CLEAR_OLD_HISTORY
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_CLEAR_OLD_HISTORY
uint64_t uniffi_nearclip_ffi_fn_method_ffinearclipmanager_clear_old_history(void*_Nonnull ptr, uint32_t days, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_CONNECT_DEVICE
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_CONNECT_DEVICE
void uniffi_nearclip_ffi_fn_method_ffinearclipmanager_connect_device(void*_Nonnull ptr, RustBuffer device_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_DISCONNECT_DEVICE
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_DISCONNECT_DEVICE
void uniffi_nearclip_ffi_fn_method_ffinearclipmanager_disconnect_device(void*_Nonnull ptr, RustBuffer device_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_GET_CONNECTED_DEVICES
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_GET_CONNECTED_DEVICES
RustBuffer uniffi_nearclip_ffi_fn_method_ffinearclipmanager_get_connected_devices(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_GET_DEVICE_HISTORY
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_GET_DEVICE_HISTORY
RustBuffer uniffi_nearclip_ffi_fn_method_ffinearclipmanager_get_device_history(void*_Nonnull ptr, RustBuffer device_id, uint64_t limit, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_GET_DEVICE_ID
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_GET_DEVICE_ID
RustBuffer uniffi_nearclip_ffi_fn_method_ffinearclipmanager_get_device_id(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_GET_DEVICE_STATUS
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_GET_DEVICE_STATUS
RustBuffer uniffi_nearclip_ffi_fn_method_ffinearclipmanager_get_device_status(void*_Nonnull ptr, RustBuffer device_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_GET_HISTORY_COUNT
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_GET_HISTORY_COUNT
uint64_t uniffi_nearclip_ffi_fn_method_ffinearclipmanager_get_history_count(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_GET_PAIRED_DEVICES
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_GET_PAIRED_DEVICES
RustBuffer uniffi_nearclip_ffi_fn_method_ffinearclipmanager_get_paired_devices(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_GET_RECENT_HISTORY
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_GET_RECENT_HISTORY
RustBuffer uniffi_nearclip_ffi_fn_method_ffinearclipmanager_get_recent_history(void*_Nonnull ptr, uint64_t limit, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_INIT_HISTORY
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_INIT_HISTORY
void uniffi_nearclip_ffi_fn_method_ffinearclipmanager_init_history(void*_Nonnull ptr, RustBuffer db_path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_IS_RUNNING
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_IS_RUNNING
int8_t uniffi_nearclip_ffi_fn_method_ffinearclipmanager_is_running(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_ON_BLE_ACK_RECEIVED
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_ON_BLE_ACK_RECEIVED
void uniffi_nearclip_ffi_fn_method_ffinearclipmanager_on_ble_ack_received(void*_Nonnull ptr, RustBuffer device_id, RustBuffer data, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_ON_BLE_CONNECTION_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_ON_BLE_CONNECTION_CHANGED
void uniffi_nearclip_ffi_fn_method_ffinearclipmanager_on_ble_connection_changed(void*_Nonnull ptr, RustBuffer device_id, int8_t connected, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_ON_BLE_DATA_RECEIVED
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_ON_BLE_DATA_RECEIVED
void uniffi_nearclip_ffi_fn_method_ffinearclipmanager_on_ble_data_received(void*_Nonnull ptr, RustBuffer device_id, RustBuffer data, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_ON_BLE_DEVICE_DISCOVERED
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_ON_BLE_DEVICE_DISCOVERED
void uniffi_nearclip_ffi_fn_method_ffinearclipmanager_on_ble_device_discovered(void*_Nonnull ptr, RustBuffer peripheral_uuid, RustBuffer device_id, RustBuffer public_key_hash, int32_t rssi, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_PAIR_DEVICE
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_PAIR_DEVICE
int8_t uniffi_nearclip_ffi_fn_method_ffinearclipmanager_pair_device(void*_Nonnull ptr, RustBuffer device, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_REMOVE_PAIRED_DEVICE
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_REMOVE_PAIRED_DEVICE
void uniffi_nearclip_ffi_fn_method_ffinearclipmanager_remove_paired_device(void*_Nonnull ptr, RustBuffer device_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_SET_BLE_HARDWARE
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_SET_BLE_HARDWARE
void uniffi_nearclip_ffi_fn_method_ffinearclipmanager_set_ble_hardware(void*_Nonnull ptr, uint64_t hardware, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_SET_DEVICE_STORAGE
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_SET_DEVICE_STORAGE
void uniffi_nearclip_ffi_fn_method_ffinearclipmanager_set_device_storage(void*_Nonnull ptr, uint64_t storage, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_START
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_START
void uniffi_nearclip_ffi_fn_method_ffinearclipmanager_start(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_START_DISCOVERY
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_START_DISCOVERY
void uniffi_nearclip_ffi_fn_method_ffinearclipmanager_start_discovery(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_STOP
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_STOP
void uniffi_nearclip_ffi_fn_method_ffinearclipmanager_stop(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_STOP_DISCOVERY
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_STOP_DISCOVERY
void uniffi_nearclip_ffi_fn_method_ffinearclipmanager_stop_discovery(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_SYNC_CLIPBOARD
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_SYNC_CLIPBOARD
void uniffi_nearclip_ffi_fn_method_ffinearclipmanager_sync_clipboard(void*_Nonnull ptr, RustBuffer content, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_TRY_CONNECT_PAIRED_DEVICES
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_TRY_CONNECT_PAIRED_DEVICES
uint32_t uniffi_nearclip_ffi_fn_method_ffinearclipmanager_try_connect_paired_devices(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_UNPAIR_DEVICE
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_METHOD_FFINEARCLIPMANAGER_UNPAIR_DEVICE
void uniffi_nearclip_ffi_fn_method_ffinearclipmanager_unpair_device(void*_Nonnull ptr, RustBuffer device_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_INIT_CALLBACK_VTABLE_FFIBLEHARDWARE
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_INIT_CALLBACK_VTABLE_FFIBLEHARDWARE
void uniffi_nearclip_ffi_fn_init_callback_vtable_ffiblehardware(UniffiVTableCallbackInterfaceFfiBleHardware* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_INIT_CALLBACK_VTABLE_FFIDEVICESTORAGE
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_INIT_CALLBACK_VTABLE_FFIDEVICESTORAGE
void uniffi_nearclip_ffi_fn_init_callback_vtable_ffidevicestorage(UniffiVTableCallbackInterfaceFfiDeviceStorage* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_INIT_CALLBACK_VTABLE_FFINEARCLIPCALLBACK
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_INIT_CALLBACK_VTABLE_FFINEARCLIPCALLBACK
void uniffi_nearclip_ffi_fn_init_callback_vtable_ffinearclipcallback(UniffiVTableCallbackInterfaceFfiNearClipCallback* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_FUNC_FLUSH_LOGS
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_FUNC_FLUSH_LOGS
void uniffi_nearclip_ffi_fn_func_flush_logs(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_FUNC_INIT_LOGGING
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_FN_FUNC_INIT_LOGGING
void uniffi_nearclip_ffi_fn_func_init_logging(RustBuffer level, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_nearclip_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_nearclip_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUSTBUFFER_FREE
void ffi_nearclip_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_nearclip_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_U8
void ffi_nearclip_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_U8
void ffi_nearclip_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_U8
void ffi_nearclip_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_nearclip_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_I8
void ffi_nearclip_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_I8
void ffi_nearclip_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_I8
void ffi_nearclip_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_nearclip_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_U16
void ffi_nearclip_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_U16
void ffi_nearclip_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_U16
void ffi_nearclip_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_nearclip_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_I16
void ffi_nearclip_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_I16
void ffi_nearclip_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_I16
void ffi_nearclip_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_nearclip_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_U32
void ffi_nearclip_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_U32
void ffi_nearclip_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_U32
void ffi_nearclip_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_nearclip_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_I32
void ffi_nearclip_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_I32
void ffi_nearclip_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_I32
void ffi_nearclip_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_nearclip_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_U64
void ffi_nearclip_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_U64
void ffi_nearclip_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_U64
void ffi_nearclip_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_nearclip_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_I64
void ffi_nearclip_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_I64
void ffi_nearclip_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_I64
void ffi_nearclip_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_nearclip_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_F32
void ffi_nearclip_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_F32
void ffi_nearclip_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_F32
void ffi_nearclip_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_nearclip_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_F64
void ffi_nearclip_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_F64
void ffi_nearclip_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_F64
void ffi_nearclip_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_nearclip_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_POINTER
void ffi_nearclip_ffi_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_POINTER
void ffi_nearclip_ffi_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_POINTER
void ffi_nearclip_ffi_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_nearclip_ffi_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_nearclip_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_nearclip_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_nearclip_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_nearclip_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_POLL_VOID
void ffi_nearclip_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_nearclip_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_FREE_VOID
void ffi_nearclip_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_nearclip_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_FUNC_FLUSH_LOGS
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_FUNC_FLUSH_LOGS
uint16_t uniffi_nearclip_ffi_checksum_func_flush_logs(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_FUNC_INIT_LOGGING
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_FUNC_INIT_LOGGING
uint16_t uniffi_nearclip_ffi_checksum_func_init_logging(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_ADD_HISTORY_ENTRY
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_ADD_HISTORY_ENTRY
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_add_history_entry(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_ADD_PAIRED_DEVICE
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_ADD_PAIRED_DEVICE
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_add_paired_device(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_CLEAR_ALL_HISTORY
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_CLEAR_ALL_HISTORY
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_clear_all_history(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_CLEAR_OLD_HISTORY
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_CLEAR_OLD_HISTORY
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_clear_old_history(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_CONNECT_DEVICE
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_CONNECT_DEVICE
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_connect_device(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_DISCONNECT_DEVICE
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_DISCONNECT_DEVICE
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_disconnect_device(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_GET_CONNECTED_DEVICES
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_GET_CONNECTED_DEVICES
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_get_connected_devices(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_GET_DEVICE_HISTORY
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_GET_DEVICE_HISTORY
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_get_device_history(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_GET_DEVICE_ID
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_GET_DEVICE_ID
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_get_device_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_GET_DEVICE_STATUS
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_GET_DEVICE_STATUS
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_get_device_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_GET_HISTORY_COUNT
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_GET_HISTORY_COUNT
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_get_history_count(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_GET_PAIRED_DEVICES
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_GET_PAIRED_DEVICES
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_get_paired_devices(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_GET_RECENT_HISTORY
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_GET_RECENT_HISTORY
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_get_recent_history(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_INIT_HISTORY
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_INIT_HISTORY
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_init_history(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_IS_RUNNING
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_IS_RUNNING
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_is_running(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_ON_BLE_ACK_RECEIVED
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_ON_BLE_ACK_RECEIVED
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_on_ble_ack_received(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_ON_BLE_CONNECTION_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_ON_BLE_CONNECTION_CHANGED
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_on_ble_connection_changed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_ON_BLE_DATA_RECEIVED
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_ON_BLE_DATA_RECEIVED
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_on_ble_data_received(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_ON_BLE_DEVICE_DISCOVERED
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_ON_BLE_DEVICE_DISCOVERED
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_on_ble_device_discovered(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_PAIR_DEVICE
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_PAIR_DEVICE
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_pair_device(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_REMOVE_PAIRED_DEVICE
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_REMOVE_PAIRED_DEVICE
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_remove_paired_device(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_SET_BLE_HARDWARE
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_SET_BLE_HARDWARE
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_set_ble_hardware(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_SET_DEVICE_STORAGE
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_SET_DEVICE_STORAGE
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_set_device_storage(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_START
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_START
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_start(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_START_DISCOVERY
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_START_DISCOVERY
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_start_discovery(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_STOP
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_STOP
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_stop(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_STOP_DISCOVERY
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_STOP_DISCOVERY
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_stop_discovery(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_SYNC_CLIPBOARD
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_SYNC_CLIPBOARD
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_sync_clipboard(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_TRY_CONNECT_PAIRED_DEVICES
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_TRY_CONNECT_PAIRED_DEVICES
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_try_connect_paired_devices(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_UNPAIR_DEVICE
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPMANAGER_UNPAIR_DEVICE
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipmanager_unpair_device(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_CONSTRUCTOR_FFINEARCLIPMANAGER_NEW
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_CONSTRUCTOR_FFINEARCLIPMANAGER_NEW
uint16_t uniffi_nearclip_ffi_checksum_constructor_ffinearclipmanager_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_START_SCAN
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_START_SCAN
uint16_t uniffi_nearclip_ffi_checksum_method_ffiblehardware_start_scan(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_STOP_SCAN
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_STOP_SCAN
uint16_t uniffi_nearclip_ffi_checksum_method_ffiblehardware_stop_scan(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_CONNECT
uint16_t uniffi_nearclip_ffi_checksum_method_ffiblehardware_connect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_DISCONNECT
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_DISCONNECT
uint16_t uniffi_nearclip_ffi_checksum_method_ffiblehardware_disconnect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_READ_CHARACTERISTIC
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_READ_CHARACTERISTIC
uint16_t uniffi_nearclip_ffi_checksum_method_ffiblehardware_read_characteristic(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_WRITE_CHARACTERISTIC
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_WRITE_CHARACTERISTIC
uint16_t uniffi_nearclip_ffi_checksum_method_ffiblehardware_write_characteristic(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_SUBSCRIBE_CHARACTERISTIC
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_SUBSCRIBE_CHARACTERISTIC
uint16_t uniffi_nearclip_ffi_checksum_method_ffiblehardware_subscribe_characteristic(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_START_ADVERTISING
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_START_ADVERTISING
uint16_t uniffi_nearclip_ffi_checksum_method_ffiblehardware_start_advertising(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_STOP_ADVERTISING
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_STOP_ADVERTISING
uint16_t uniffi_nearclip_ffi_checksum_method_ffiblehardware_stop_advertising(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_IS_CONNECTED
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_IS_CONNECTED
uint16_t uniffi_nearclip_ffi_checksum_method_ffiblehardware_is_connected(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_GET_MTU
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIBLEHARDWARE_GET_MTU
uint16_t uniffi_nearclip_ffi_checksum_method_ffiblehardware_get_mtu(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIDEVICESTORAGE_SAVE_DEVICE
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIDEVICESTORAGE_SAVE_DEVICE
uint16_t uniffi_nearclip_ffi_checksum_method_ffidevicestorage_save_device(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIDEVICESTORAGE_REMOVE_DEVICE
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIDEVICESTORAGE_REMOVE_DEVICE
uint16_t uniffi_nearclip_ffi_checksum_method_ffidevicestorage_remove_device(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIDEVICESTORAGE_LOAD_ALL_DEVICES
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFIDEVICESTORAGE_LOAD_ALL_DEVICES
uint16_t uniffi_nearclip_ffi_checksum_method_ffidevicestorage_load_all_devices(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPCALLBACK_ON_DEVICE_CONNECTED
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPCALLBACK_ON_DEVICE_CONNECTED
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipcallback_on_device_connected(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPCALLBACK_ON_DEVICE_DISCONNECTED
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPCALLBACK_ON_DEVICE_DISCONNECTED
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipcallback_on_device_disconnected(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPCALLBACK_ON_DEVICE_UNPAIRED
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPCALLBACK_ON_DEVICE_UNPAIRED
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipcallback_on_device_unpaired(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPCALLBACK_ON_PAIRING_REJECTED
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPCALLBACK_ON_PAIRING_REJECTED
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipcallback_on_pairing_rejected(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPCALLBACK_ON_CLIPBOARD_RECEIVED
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPCALLBACK_ON_CLIPBOARD_RECEIVED
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipcallback_on_clipboard_received(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPCALLBACK_ON_SYNC_ERROR
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPCALLBACK_ON_SYNC_ERROR
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipcallback_on_sync_error(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPCALLBACK_ON_DEVICE_DISCOVERED
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPCALLBACK_ON_DEVICE_DISCOVERED
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipcallback_on_device_discovered(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPCALLBACK_ON_DEVICE_LOST
#define UNIFFI_FFIDEF_UNIFFI_NEARCLIP_FFI_CHECKSUM_METHOD_FFINEARCLIPCALLBACK_ON_DEVICE_LOST
uint16_t uniffi_nearclip_ffi_checksum_method_ffinearclipcallback_on_device_lost(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_NEARCLIP_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_nearclip_ffi_uniffi_contract_version(void
    
);
#endif

